package com.example.infoapptest;

import android.annotation.SuppressLint;
import android.os.Handler;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.view.animation.AnimationUtils;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;

import com.example.infoapptest.databinding.ItemPlanetBinding;

import java.util.ArrayList;
import java.util.List;

public class PlanetsAdapter extends RecyclerView.Adapter<PlanetsAdapter.PlanetViewHolder> {
    private static OnDetailsClickListener listener;

    public void setListener(OnDetailsClickListener listener) {
        PlanetsAdapter.listener = listener;
    }

    @FunctionalInterface
    public interface OnDetailsClickListener {
        void onClick(int position);
    }

    public static class PlanetViewHolder extends RecyclerView.ViewHolder {
        Handler handler = new Handler();
        private final ImageView image;
        private final TextView planetName;
        private final TextView description;
        private final TextView planetNumber;
        private final ConstraintLayout root;


        public PlanetViewHolder(@NonNull View itemView) {
            super(itemView);
            ItemPlanetBinding binding = ItemPlanetBinding.bind(itemView);
            image = binding.image;
            planetName = binding.planetName;
            description = binding.description;
            planetNumber = binding.planetNumber;
            binding.detailsButton.setOnClickListener(v -> {
                listener.onClick(getAdapterPosition());
            });
            root = binding.getRoot();
        }

        @SuppressLint("SetTextI18n")
        public void bind(int pos) {
            PlanetData planet = planets.get(pos);
            image.setImageResource(planet.getImageResId());
            planetName.setText(planet.getName());
            description.setText(planet.getTitle());
            planetNumber.setText(String.valueOf(pos + 1));
            root.startAnimation(AnimationUtils.loadAnimation(itemView.getContext(), R.anim.anim_planets));
        }
    }

    @NonNull
    @Override
    public PlanetsAdapter.PlanetViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View itemView = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_planet, parent, false);
        return new PlanetsAdapter.PlanetViewHolder(itemView);
    }

    @Override
    public void onBindViewHolder(@NonNull PlanetsAdapter.PlanetViewHolder holder, int position) {
        holder.bind(position);
    }

    @Override
    public int getItemCount() {
        return planets.size();
    }

    public static final List<PlanetData> planets = new ArrayList<>();

    static {
        planets.add(new PlanetData(R.drawable.mercury, "Mercury", "The swiftest planet.", " Overview:\nMercury is the smallest and innermost planet in our solar system. It is named after the Roman god Mercury, known for his speed and agility. Mercury is a rocky, terrestrial planet with a surface that is heavily cratered.\n\n Size and Distance:\nMercury has a diameter of approximately 4,879 kilometers (3,032 miles), making it the smallest planet in the solar system. It orbits the Sun at an average distance of about 57.9 million kilometers (36 million miles).\n\n Orbital and Rotational Characteristics:\nMercury has the fastest orbit around the Sun, completing one revolution in about 88 Earth days. It also has the slowest rotation on its axis among all the planets, taking about 59 Earth days for a single rotation. Mercury has a unique 3:2 spin-orbit resonance, which means it rotates three times on its axis for every two orbits around the Sun.\n\n Surface Features:\nMercury's surface is characterized by numerous impact craters, similar to the Moon. It has vast plains, cliffs, ridges, and scarps caused by tectonic activity. One of the most prominent surface features is the Caloris Basin, a large impact crater spanning about 1,550 kilometers (960 miles) in diameter.\n\n Extreme Temperatures:\nDue to its proximity to the Sun and lack of a substantial atmosphere, Mercury experiences extreme temperature variations. It has one of the most significant temperature ranges among all the planets, with daytime temperatures reaching around 430 degrees Celsius (800 degrees Fahrenheit) and dropping to about -180 degrees Celsius (-290 degrees Fahrenheit) at night.\n\n Composition and Atmosphere:\nMercury is primarily composed of rock and metal, with a relatively high density. It has a very thin atmosphere called an exosphere, which consists of trace amounts of hydrogen, helium, oxygen, sodium, calcium, and potassium. The exosphere is so sparse that the particles rarely collide with each other.\n\n Lack of Moons and Rings:\nUnlike many other planets in the solar system, Mercury does not have any moons or rings.\n\n Exploration:\nSeveral missions have been sent to study Mercury, including NASA's Mariner 10 and MESSENGER (MErcury Surface, Space ENvironment, GEochemistry, and Ranging) missions. The MESSENGER spacecraft provided valuable data about Mercury's surface, composition, and magnetic field."));
        planets.add(new PlanetData(R.drawable.venus, "Venus", "Earth's superheated twin sister.", " Overview:\nVenus is the second planet from the Sun and is named after the Roman goddess of love and beauty. It is often referred to as Earth's \"sister planet\" due to its similar size and composition. Venus is a rocky, terrestrial planet with a thick atmosphere.\n\n Size and Distance:\nVenus has a diameter of approximately 12,104 kilometers (7,521 miles), making it slightly smaller than Earth. It orbits the Sun at an average distance of about 108 million kilometers (67 million miles).\n\n Orbital and Rotational Characteristics:\nVenus has a relatively slow rotation on its axis, taking about 243 Earth days for a single rotation, making it the slowest rotation of any planet in the solar system. It has a retrograde rotation, meaning it rotates in the opposite direction to its orbit around the Sun. Venus completes one orbit around the Sun in about 225 Earth days.\n\n Atmosphere:\nVenus has an extremely dense and predominantly carbon dioxide atmosphere, with thick clouds of sulfuric acid. The atmosphere creates a runaway greenhouse effect, resulting in a surface temperature that is the hottest among all the planets in the solar system, averaging around 462 degrees Celsius (864 degrees Fahrenheit).\n\n Surface Features:\nThe surface of Venus is mainly composed of volcanic plains, with thousands of volcanic structures and lava flows. It has few impact craters, indicating a relatively young surface. Venus also has highland regions, mountain ranges, and large impact craters.\n\n Exploration:\nSeveral missions have been sent to study Venus, including NASA's Mariner and Magellan missions, as well as the European Space Agency's Venus Express mission. These missions have provided valuable data about Venus' atmosphere, surface, and geological features."));
        planets.add(new PlanetData(R.drawable.earth, "Earth", "Our homeworld.", " Overview:\nEarth is the third planet from the Sun and is the only known celestial body to support life. It is the fifth-largest planet in the solar system and is often referred to as the Blue Planet due to its abundant water on the surface.\n\n Size and Distance:\nEarth has a diameter of approximately 12,742 kilometers (7,918 miles) and orbits the Sun at an average distance of about 149.6 million kilometers (93 million miles).\n\n Orbital and Rotational Characteristics:\nEarth has an elliptical orbit around the Sun, completing one revolution in approximately 365.25 days, giving rise to our calendar year. It rotates on its axis once every 24 hours, resulting in day and night cycles.\n\n Atmosphere:\nEarth has a diverse atmosphere composed primarily of nitrogen (about 78%) and oxygen (about 21%), with trace amounts of other gases such as carbon dioxide, water vapor, and noble gases. The atmosphere plays a crucial role in regulating temperature, protecting life from harmful radiation, and facilitating weather patterns.\n\n Surface Features:\nEarth's surface is predominantly covered by oceans, which account for about 71% of the planet's surface area. The remaining 29% consists of continents, islands, mountains, deserts, forests, and various landforms shaped by geological processes such as erosion, tectonic activity, and weathering.\n\n Biosphere:\nEarth's biosphere encompasses all the ecosystems and living organisms on the planet. It supports a remarkable diversity of life, ranging from microscopic bacteria to complex organisms like plants, animals, and humans. The biosphere interacts with the atmosphere, hydrosphere, and lithosphere, forming intricate ecological relationships.\n\n Climate:\nEarth experiences a wide range of climates due to its axial tilt and varying distances from the Sun throughout its orbit. This results in diverse climatic zones, including tropical, temperate, and polar regions. Climate patterns are influenced by factors such as solar radiation, atmospheric circulation, ocean currents, and geological features.\n\n Exploration:\nHumans have extensively explored and studied Earth. Satellites, weather stations, and scientific research expeditions have provided valuable insights into Earth's geology, weather patterns, ecosystems, and the impact of human activities on the planet."));
        planets.add(new PlanetData(R.drawable.mars, "Mars", "The red planet.", " Overview:\nMars is the fourth planet from the Sun and is often called the \"Red Planet\" due to its reddish appearance. It is a rocky, terrestrial planet with a thin atmosphere.\n\n Size and Distance:\nMars has a diameter of approximately 6,779 kilometers (4,212 miles), making it about half the size of Earth. It orbits the Sun at an average distance of about 227.9 million kilometers (141.6 million miles).\n\n Orbital and Rotational Characteristics:\nMars has an orbital period of about 687 Earth days, completing one revolution around the Sun. It rotates on its axis, giving it a day length very similar to Earth, with a Martian day, called a sol, lasting about 24 hours and 37 minutes.\n\n Atmosphere:\nMars has a thin atmosphere composed primarily of carbon dioxide (about 95.3%). It also contains traces of nitrogen, argon, and oxygen. The thin atmosphere creates a greenhouse effect but is not sufficient to support human life or protect the planet from harmful radiation.\n\n Surface Features:\nMars has a diverse range of surface features, including vast plains, towering volcanoes, deep canyons, and impact craters. The most notable feature is Olympus Mons, the largest volcano and the tallest known volcano in the solar system. Mars also has Valles Marineris, a system of canyons that stretches for thousands of kilometers.\n\n Polar Ice Caps:\nMars has polar ice caps composed mainly of water ice and frozen carbon dioxide. These ice caps are subject to seasonal variations, expanding and contracting with the changing Martian seasons.\n\n Possibility of Life:\nMars has been a subject of interest in the search for extraterrestrial life. While no definitive evidence of past or present life has been found, scientists have discovered evidence of liquid water in the past, suggesting the potential for microbial life.\n\n Exploration:\nMars has been the focus of numerous space missions. Several orbiters, landers, and rovers have been sent by space agencies such as NASA, ESA, and others to study the planet's surface, atmosphere, and search for signs of past or present life.\n"));
        planets.add(new PlanetData(R.drawable.jupiter, "Jupiter", "King of the planets", " Overview:\nJupiter is the largest planet in our solar system and is known for its immense size and distinctive banded appearance. It is a gas giant composed mainly of hydrogen and helium and is often referred to as a \"failed star\" due to its similarity in composition to a star.\n\n Size and Distance:\nJupiter has a diameter of approximately 139,820 kilometers (86,881 miles), making it more than 11 times the diameter of Earth. It is located about 778.5 million kilometers (484 million miles) from the Sun and is the fifth planet from the Sun.\n\n Orbital and Rotational Characteristics:\nJupiter orbits the Sun with an average distance of about 778.5 million kilometers (484 million miles) and completes one orbit in approximately 11.86 Earth years. It has a rapid rotation, with a day on Jupiter lasting about 9.9 Earth hours.\n\n Atmosphere:\nJupiter has a thick atmosphere primarily composed of hydrogen (about 75%) and helium (about 24%). It also contains trace amounts of other gases, including methane, ammonia, water vapor, and various hydrocarbons. The atmosphere gives Jupiter its distinct bands and zones, with swirling storms and the iconic Great Red Spot.\n\n Great Red Spot:\nThe Great Red Spot is a persistent storm on Jupiter that has been observed for centuries. It is a massive storm system larger than Earth, with swirling clouds and high winds. While it has been shrinking in recent years, it remains a prominent feature on the planet.\n\n Moons:\nJupiter has a large number of moons, with over 80 known moons orbiting the planet. The four largest moons, known as the Galilean moons, are Io, Europa, Ganymede, and Callisto. These moons are some of the most geologically active objects in the solar system and have been the focus of exploration.\n\n Rings:\nJupiter has a faint system of rings composed of tiny particles of dust and rock. These rings are much less prominent than the rings of Saturn but have been detected through spacecraft observations.\n\n Exploration:\nJupiter has been extensively studied by various space missions. Notable missions include NASA's Pioneer, Voyager, Galileo, and Juno missions, as well as the European Space Agency's JUICE mission (JUpiter ICy moons Explorer), which is planned for launch in the 2020s."));
        planets.add(new PlanetData(R.drawable.saturn, "Saturn", "Jewel of the solar system", " Overview:\nSaturn is the sixth planet from the Sun and is known for its stunning ring system. It is a gas giant and is the second-largest planet in our solar system.\n\n Size and Distance:\nSaturn has a diameter of approximately 116,460 kilometers (72,367 miles), making it the second-largest planet after Jupiter. It is located about 1.4 billion kilometers (886 million miles) from the Sun and is the second farthest planet from it.\n\n Orbital and Rotational Characteristics:\nSaturn orbits the Sun with an average distance of about 1.4 billion kilometers (886 million miles) and completes one orbit in approximately 29.5 Earth years. It has a relatively fast rotation, with a day on Saturn lasting about 10.7 Earth hours.\n\n Rings:\nSaturn is famous for its spectacular ring system, which consists of thousands of individual rings made up of ice particles and rocky debris. The rings are separated by gaps, and they extend outward from the planet's surface for tens of thousands of kilometers. The rings are composed mainly of water ice, with traces of other materials.\n\n Atmosphere:\nSaturn has a thick atmosphere primarily composed of hydrogen (about 96%) and helium (about 3%). It also contains trace amounts of other gases, including methane, ammonia, and water vapor. The atmosphere gives Saturn its yellowish color and features bands of clouds.\n\n Moons:\nSaturn has an extensive moon system, with at least 82 known moons orbiting the planet. The largest moon, Titan, is larger than the planet Mercury and has a dense atmosphere. Other notable moons include Enceladus, known for its geysers of water vapor, and Mimas, which has a distinctive impact crater resembling the \"Death Star\" from Star Wars.\n\n Exploration:\nSaturn has been the target of several space missions. The Cassini-Huygens mission, a collaboration between NASA, ESA, and the Italian Space Agency, explored Saturn and its moons from 2004 to 2017. The mission provided valuable data about the planet, its rings, and its moons. Future missions are also being planned to study Saturn and its moon Titan further."));
        planets.add(new PlanetData(R.drawable.uranus, "Uranus", "The original ice giant", " Overview:\nUranus is the seventh planet from the Sun and is classified as an ice giant. It is named after the Greek god of the sky. Uranus is known for its unique feature of rotating on its side, with its axis of rotation tilted almost 98 degrees relative to its orbit.\n\n Size and Distance:\nUranus has a diameter of approximately 51,118 kilometers (31,763 miles), making it the third-largest planet in our solar system. It is located about 2.9 billion kilometers (1.8 billion miles) from the Sun, making it the third farthest planet from it.\n\n Orbital and Rotational Characteristics:\nUranus orbits the Sun with an average distance of about 2.9 billion kilometers (1.8 billion miles) and completes one orbit in approximately 84 Earth years. Due to its extreme axial tilt, Uranus experiences long seasons, with each pole facing the Sun for about 21 years.\n\n Atmosphere:\nUranus has a primarily hydrogen and helium atmosphere, similar to Jupiter and Saturn, but it also contains significant amounts of methane. The methane in the upper atmosphere gives Uranus its distinct blue-green color. Uranus has faint cloud bands and occasional storms.\n\n Rings:\nUranus has a system of rings, although they are much less prominent and fainter compared to the rings of Saturn. The rings are composed of dark particles, possibly made up of ice and organic compounds. They were discovered in 1977 when Uranus passed in front of a star, causing a temporary dip in its brightness.\n\n Moons:\nUranus has a total of 27 known moons. The five largest moons are Miranda, Ariel, Umbriel, Titania, and Oberon. Miranda is particularly interesting due to its varied and geologically diverse terrain, including cliffs, canyons, and craters.\n\n Exploration:\nUranus has been visited by only one spacecraft to date. In 1986, NASA's Voyager 2 spacecraft flew by Uranus, providing the most detailed images and data of the planet and its moons. There are currently no specific future missions planned to explore Uranus."));
        planets.add(new PlanetData(R.drawable.neptune, "Neptune", "The farthest planet in our solar system", " Overview:\nNeptune is the eighth and farthest known planet from the Sun in our solar system. It is a gas giant and is often referred to as an \"ice giant\" due to its composition of primarily icy materials and gases.\n\n Size and Distance:\nNeptune has a diameter of approximately 49,528 kilometers (30,775 miles), making it the fourth-largest planet in our solar system. It is located about 4.5 billion kilometers (2.8 billion miles) from the Sun, making it the farthest planet from it.\n\n Orbital and Rotational Characteristics:\nNeptune orbits the Sun with an average distance of about 4.5 billion kilometers (2.8 billion miles) and completes one orbit in approximately 165 Earth years. It has a relatively fast rotation, with a day on Neptune lasting about 16.1 Earth hours.\n\n Atmosphere:\nNeptune has a thick atmosphere primarily composed of hydrogen (about 80%) and helium (about 19%). It also contains trace amounts of methane, which gives the planet its distinctive blue color. The atmosphere of Neptune is known for its dynamic weather patterns and the presence of large storm systems, such as the Great Dark Spot observed by the Voyager 2 spacecraft.\n\n Rings:\nNeptune has a system of rings, although they are much fainter and less prominent compared to the rings of Saturn. The rings are composed of dust particles and rocky debris, and they are believed to be relatively young compared to the rings of other gas giants.\n\n Moons:\nNeptune has a total of 14 known moons, with the largest and most well-known moon being Triton. Triton is unique among large moons in the solar system as it orbits Neptune in a retrograde direction, opposite to the planet's rotation. Triton is geologically active and has cryovolcanoes that erupt nitrogen gas and dust.\n\n Exploration:\nNeptune has been visited by only one spacecraft, NASA's Voyager 2. It flew by Neptune in 1989, providing valuable data and detailed images of the planet, its rings, and its moons. There are currently no specific future missions planned to explore Neptune"));
    }
}